

(* Nodes process local events. 

   local events can be either:
   . 'meta' events generated by the simulator, they can be used to start/stop a
      node or to inform it of a topology change,
   . or application level-messages. In that case, local addressing is used
     for message emission and reception. *)
type t = 
  | Meta of Mevent.t
  | Protocol of Message.t * Local_id.t

val to_string : t -> string