(* meta events are generated by the simulator/scheduler and are all events
   which are not application level messages. This includes Start signal
   but they can be used to simulate node failure, or signal topology changes *)

type t = 
  | Start

val to_string : t -> string